# Creating Numpy Arrays From Sequnce


In [ ]:
[1,2,3] (1,2,3)



In [23]:
d1 ={1:1,2:2,3:3}

In [26]:
type(d1)

dict

In [27]:
my_set = {1,2,3}
type(my_set)

set

In [28]:
np.array(my_set)

array({1, 2, 3}, dtype=object)

In [3]:
import numpy as np

In [2]:
np.array((1,2,3))

array([1, 2, 3])

In [29]:
a1 = np.array([1,2,3])

In [31]:
a1

array([1, 2, 3])

In [32]:
a1[0]

1

In [21]:
np.array({1:1,2:2,3:3})

array({1: 1, 2: 2, 3: 3}, dtype=object)

In [12]:
type(a1) 

numpy.ndarray

In [14]:
a2

array({1, 2, 3}, dtype=object)

In [16]:
a2.shape

()

In [18]:
a2

array({1, 2, 3}, dtype=object)

In [37]:
a2[()]

{1, 2, 3}

In [43]:
a5 = np.array(3)

In [42]:
a5[()]

3

# DTYPE

In [45]:
a = np.array([1,2,3])

In [47]:
type(a[0]),type(5)

(numpy.int64, int)

In [70]:
a1 = np.array([1,2,0],dtype = float )

In [71]:
a

array([1, 2, 3])

In [72]:
type(a1[0])

numpy.float64

In [74]:
# Range ? Function 

In [76]:
list(range(0,3))

[0, 1, 2]

In [77]:
list(range(3))

[0, 1, 2]

In [78]:
np.arange(3)

array([0, 1, 2])

In [81]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [83]:
range(1,5.5)

TypeError: 'float' object cannot be interpreted as an integer

In [84]:
np.arange(1,5.5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
[1,2,3,4,5,6,7,8,9]

[1,2,3,
 4,5,6,
 7,8,9]


4,2

In [85]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
np.arange(1,9).reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [89]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [90]:
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [107]:
np.arange(1,17,dtype=float).reshape(16,1)

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.],
       [15.],
       [16.]])

# Np zeros and One

In [109]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [108]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [110]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [116]:
np.random.random((3,3))

array([[0.9314039 , 0.51060365, 0.26903726],
       [0.07102941, 0.96734745, 0.71853444],
       [0.4839768 , 0.34241906, 0.89824334]])

# Linspace

In [118]:
Signature:
np.linspace(
    start,
    stop,
    num=50,
    dtype=None,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].




np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [ ]:
np.linspace(-10,10,4)

In [122]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,1,4)

In [124]:
np.linspace(-10,10,4)

array([-10.        ,  -3.33333333,   3.33333333,  10.        ])

In [125]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [126]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [127]:
a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [129]:
a1.shape,a2.shape,a3.shape

((10,), (3, 4), (2, 2, 2))

In [130]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [132]:
a1.size,a2.size,a3.size

(10, 12, 8)

In [135]:
a1.itemsize * a1.size

40

In [140]:
noneArray = np.array([None,None])

In [145]:
print(noneArray[0])

None


In [148]:
noneArray.itemsize

8

In [150]:
print(a1.dtype),print(type(a1))

int32
<class 'numpy.ndarray'>


(None, None)

# Changing Data Type

In [168]:
a1 = a1.astype(np.float_)

In [169]:
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Array Operations

In [170]:
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [174]:
a1[0:5:2]

array([0., 2., 4.])

In [175]:
# Scaler Operations

In [178]:
a1 * 5,a1/5,a1+5,a1-5,a1%5,a1//5,a1**5

(array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.]),
 array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8]),
 array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.]),
 array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.]),
 array([0., 1., 2., 3., 4., 0., 1., 2., 3., 4.]),
 array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]),
 array([0.0000e+00, 1.0000e+00, 3.2000e+01, 2.4300e+02, 1.0240e+03,
        3.1250e+03, 7.7760e+03, 1.6807e+04, 3.2768e+04, 5.9049e+04]))

In [180]:
a1%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [181]:
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [182]:
a1>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [183]:
a1[a1>5]

array([6., 7., 8., 9.])

# Array Functions

In [189]:
a1 = np.random.random((3,3))* 10000
a1

array([[6521.79246725, 9416.89483245,  610.66044554],
       [1336.30609112, 6459.37134175, 8228.85349831],
       [2612.83464258, 8203.92583093, 5741.79993231]])

In [192]:
a1.max()

9416.89483244611

In [194]:
# min max sum product mean median mode trignometric 


np.max(a1),np.min(a1),np.prod(a1),np.mean(a1),np.median(a1),np.sin(a1),np.cos(a1)

(9416.89483244611,
 610.660445536817,
 3.2786248250900506e+32,
 5459.159898025916,
 6459.371341746441,
 array([[-0.15327501, -0.99957527,  0.92891458],
        [-0.90407627,  0.25403125, -0.85332961],
        [-0.8251373 , -0.94162078, -0.85803865]]),
 array([[ 0.98818357, -0.02914256,  0.37029408],
        [-0.42737114,  0.96719601, -0.52137181],
        [ 0.56493223, -0.33667538,  0.51358513]]))

In [197]:
a2 = np.arange(1,10).reshape(3,3)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [198]:
# 0-> column

np.max(a2,axis=0)

array([7, 8, 9])

In [200]:
# 1-> row

np.mean(a2,axis=1)

array([2., 5., 8.])

In [201]:
np.mean(a2,axis=0)

array([4., 5., 6.])

In [203]:
np.dot(np.arange(1,7).reshape(2,3),np.arange(7,13).reshape(3,2))

array([[ 58,  64],
       [139, 154]])

# Iterate on an Array

In [204]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [205]:
a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [206]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
l1 = [1,2,3]

In [212]:
l1 = [[1,2],[1,2],[1,2]]

for i in l1:
    for j in i:
        print(j)

1
2
1
2
1
2


In [209]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [210]:
for i in a2:
    for j in i:
        print(j)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [211]:
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [215]:
for i in a3:
    for j  in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7


In [216]:
for element in np.nditer(a3): # iterating over an nd array -> nditer
    print(element)

0
1
2
3
4
5
6
7


In [221]:
for element in np.ravel(a3):
    print(element)
    
    


0
1
2
3
4
5
6
7


# Stacking of An array

In [254]:

a4 = np.arange(12,dtype=float).reshape(3,4)
a5 = np.arange(12,24,dtype=np.int32).reshape(3,4)
a4,a5

NameError: name 'int32' is not defined

In [242]:
np.vstack((a4,a5)) # column must be same

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [245]:
np.hstack((a4,a5)) # row must be same

array([[ 0.,  1.,  2.,  3., 12., 13., 14., 15.],
       [ 4.,  5.,  6.,  7., 16., 17., 18., 19.],
       [ 8.,  9., 10., 11., 20., 21., 22., 23.]])

In [229]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [250]:
np.hsplit(a4,2)

[array([[0., 1.],
        [4., 5.],
        [8., 9.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.]])]

In [252]:
np.vsplit(a4,3)

[array([[0., 1., 2., 3.]]),
 array([[4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.]])]

# Vector operation 

In [264]:

a7 = np.arange(12,dtype=float).reshape(3,4)
a8 = np.arange(12,24,dtype=np.int32).reshape(3,4)

In [257]:

a4 = np.arange(4,dtype=float).reshape(2,2)
a5 = np.arange(4,dtype=np.int32).reshape(2,2)
a4,a5

(array([[0., 1.],
        [2., 3.]]),
 array([[0, 1],
        [2, 3]], dtype=int32))

In [258]:
a4 * a5

array([[0., 1.],
       [4., 9.]])

In [261]:
a6 = np.array([1,2])
a6

array([1, 2])

In [262]:
a5*a6

array([[0, 2],
       [2, 6]])

In [265]:
np.dot(a4,a7)

ValueError: shapes (2,2) and (3,4) not aligned: 2 (dim 1) != 3 (dim 0)

In [266]:
a7,a4

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[0., 1.],
        [2., 3.]]))

In [269]:
a4

array([[0., 1.],
       [2., 3.]])

In [271]:
a9 = np.arange(0,8).reshape(2,4)

In [272]:
a9,a4

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[0., 1.],
        [2., 3.]]))

In [275]:
a4+a9

ValueError: operands could not be broadcast together with shapes (2,2) (2,4) 

In [277]:
# Define two matrices for matrix multiplication
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
matmul_result = np.matmul(matrix_a, matrix_b)
matmul_result

array([[ 58,  64],
       [139, 154]])

In [280]:
np.dot(matrix_a,matrix_b) 

array([[ 58,  64],
       [139, 154]])

In [283]:
matrix_a.shape

(2, 3)

In [284]:
vector_a.shape



(3,)

In [297]:
vector_a = np.array([2, 3, 4])
vector_b = np.array([1, 5, 6])

vector_c = np.array([1,2,3,4])
np.matmul(vector_a, vector_b)

41

In [282]:
np.dot(vector_a, vector_b)

41

In [296]:
print(np.dot(matrix_a,vector_c))

ValueError: shapes (2,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)

In [295]:
print(np.matmul(matrix_a,vector_c))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [316]:
a11= np.arange(0,9).reshape(3,3)

In [317]:
a12 = np.arange(0,6).reshape(3,2)

In [298]:
a4

array([[0., 1.],
       [2., 3.]])

In [309]:
a5 = np.array([1,2])
a4,a5

(array([[0., 1.],
        [2., 3.]]),
 array([1, 2]))

In [312]:
a4 * a5

array([[0., 2.],
       [2., 6.]])

In [313]:
np.dot(a4,a5)

array([2., 8.])

In [314]:
np.matmul(a4,a5)

array([2., 8.])

In [318]:
a11,a12

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 1],
        [2, 3],
        [4, 5]]))

In [321]:
a11 + a12

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [319]:
np.dot(a11,a12)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [320]:
np.matmul(a11,a12)

array([[10, 13],
       [28, 40],
       [46, 67]])

In [ ]:
np.dot

In [ ]:
np.matmul