# Broadcasting in NumPy

Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations. The term broadcasting describes how NumPy automatically adjusts the shape of arrays with smaller dimensions to match the shape of arrays with larger dimensions in certain operations.

## Broadcasting Rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., right-most) dimensions and works its way left. Two dimensions are compatible for broadcasting if:
1. They are equal, or
2. One of them is 1

If these conditions are not met, a `ValueError: operands could not be broadcast together` is thrown.

## Examples of Broadcasting

Let's explore some examples to understand where broadcasting applies and where it does not.

### Example 1: Adding a Scalar to an Array

In this example, a scalar (single value) is added to an array. The scalar is stretched to match the shape of the array.

In [1]:
import numpy as np

arr = np.array([1, 2, 3])
scalar = 5
result = arr + scalar
print("Array:", arr)
print("Scalar:", scalar)
print("Result:", result)

Array: [1 2 3]
Scalar: 5
Result: [6 7 8]


### Example 2: Adding Arrays with Compatible Shapes

Here, we add two arrays of different shapes, but compatible for broadcasting. One array has shape (3,) and the other has shape (3, 1).

In [2]:
arr1 = np.array([1, 2, 3])     # Shape (3,)
arr2 = np.array([[4], [5], [6]])  # Shape (3, 1)
result = arr1 + arr2
print("Array 1:", arr1)
print("Array 2:\n", arr2)
print("Result:\n", result)

Array 1: [1 2 3]
Array 2:
 [[4]
 [5]
 [6]]
Result:
 [[ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]]


### Example 3: Multiplying Arrays with Compatible Shapes

This example multiplies two arrays where one is (2, 3) and the other is (3,).

In [3]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([10, 20, 30])            # Shape (3,)
result = arr1 * arr2
print("Array 1:\n", arr1)
print("Array 2:", arr2)
print("Result:\n", result)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2: [10 20 30]
Result:
 [[ 10  40  90]
 [ 40 100 180]]


### Example 4: Adding Arrays with Incompatible Shapes

Here, we attempt to add two arrays with incompatible shapes. This will result in a ValueError.

In [4]:
arr1 = np.array([1, 2, 3])  # Shape (3,)
arr2 = np.array([[1, 2], [3, 4], [5, 6]])  # Shape (3, 2)
try:
    result = arr1 + arr2
except ValueError as e:
    print("Error:", e)

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

Error: operands could not be broadcast together with shapes (3,) (3,2) 


### Example 5: Broadcasting in Higher Dimensions

Broadcasting can also work in higher dimensions. Consider the following example.

In [5]:
arr1 = np.ones((4, 3, 2))    # Shape (4, 3, 2)
arr2 = np.array([2, 3])      # Shape (2,)
result = arr1 * arr2
print("Array 1 shape:", arr1.shape)
print("Array 2 shape:", arr2.shape)
print("Result shape:", result.shape)
print("Result:\n", result)

Array 1 shape: (4, 3, 2)
Array 2 shape: (2,)
Result shape: (4, 3, 2)
Result:
 [[[2. 3.]
  [2. 3.]
  [2. 3.]]

 [[2. 3.]
  [2. 3.]
  [2. 3.]]

 [[2. 3.]
  [2. 3.]
  [2. 3.]]

 [[2. 3.]
  [2. 3.]
  [2. 3.]]]


### Example 6: Practical Example - Normalizing Rows of a Matrix

A common use of broadcasting is in normalizing data. Here, we normalize the rows of a 2D array.

In [6]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_sums = matrix.sum(axis=1).reshape(-1, 1)  # Shape (3, 1)
normalized_matrix = matrix / row_sums
print("Matrix:\n", matrix)
print("Row sums:\n", row_sums)
print("Normalized matrix:\n", normalized_matrix)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row sums:
 [[ 6]
 [15]
 [24]]
Normalized matrix:
 [[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]
 [0.29166667 0.33333333 0.375     ]]


### Example 7: Broadcasting with Different Dimensions

Consider the case where we need to add a 1D array to a 2D array.

In [7]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Shape (3, 3)
arr2 = np.array([1, 0, 1])                          # Shape (3,)
result = arr1 + arr2
print("Array 1:\n", arr1)
print("Array 2:", arr2)
print("Result:\n", result)

Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2: [1 0 1]
Result:
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


## Conclusion

Broadcasting is a powerful feature in NumPy that allows for efficient computation by avoiding unnecessary data replication. By understanding the rules of broadcasting, you can leverage this feature to write more concise and efficient code.

### Key Points:
- Broadcasting rules: dimensions must be equal or one of them must be 1.
- Broadcasting starts from the trailing dimensions and works its way left.
- Practical applications include element-wise operations, normalizing data, and more.

Experiment with different shapes and operations to gain a deeper understanding of broadcasting in NumPy.